# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10

# Wheel & Steer
steer_drive_controller:
  type                          : "steer_drive_controller/SteerDriveController"
  rear_wheel                    : 'chassis_wheel_joint'
  front_steer                   : 'chassis_steer_joint'
  publish_rate                  : 1

  pose_covariance_diagonal      : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  twist_covariance_diagonal     : [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  wheel_separation_h_multiplier : 1.0 # calibration parameter for angle odometory
  wheel_radius_multiplier       : 1.0 # calibration parameter for linear odometory
  steer_pos_multiplier          : 1.0
  cmd_vel_timeout               : 1.0
  base_frame_id                 : base_link

  #enable_odom_tf: false
  wheel_separation_h            : 1.582
  wheel_radius                  : 0.272

  linear:
    x:
      has_velocity_limits       : true
      max_velocity              : 1.0  # m/s
      min_velocity              : -1.0 # m/s
      has_acceleration_limits   : true
      max_acceleration          : 0.5 # m/s^2
      min_acceleration          : -0.5 # m/s^2
      has_jerk_limits           : false
#      max_jerk                  : 5.0 # m/s^3
  angular:
    z:
      has_velocity_limits       : true
      max_velocity              : 1.0 # 1.0  # rad/s
      has_acceleration_limits   : true
      max_acceleration          : 2.0 # 1.0  # rad/s^2
      has_jerk_limits           : false
#      max_jerk                  : 0.5 # rad/s^3
